require:
  - rubocop-rails

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
    - '**/*.rake'
    - 'config.ru'
    - 'Rakefile'
    - 'config/**/*'
    - 'test/**/*'
    - 'script/**/*'
    - 'buildspecs/**/*'
    - 'harness/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - '.github/**/*'
    - '.direnv/**/*'
